name    'jasper-sonos'
version '0.1.4'
source 'git://github.com/jasperla/puppet-sonos.git'
author 'Jasper Lievisse Adriaanse'
license 'ISC'
summary 'Manage Sonos systems'
description 'Manage Sonos systems (currently only speakers)'
project_page 'https://github.com/jasperla/puppet-sonos'
